test
Signed-off-by: oliver könig <okoenig@nvidia.com>

diff --git a/.github/actions/test-template/action.yml b/.github/actions/test-template/action.yml
--- a/.github/actions/test-template/action.yml
+++ b/.github/actions/test-template/action.yml
@@ -185,115 +185,115 @@ runs:
           --secret id=GH_TOKEN \
           -t export-deploy .
 
-    - name: Start container
-      shell: bash
-      env:
-        MNT_PATH: ${{ steps.azure-fileshare.outputs.MNT_PATH }}
-        MOUNT_FS: ${{ inputs.has-azure-credentials == 'true' && inputs.is_unit_test == 'false' }}
-      run: |
-        ARG=("")
+    # - name: Start container
+    #   shell: bash
+    #   env:
+    #     MNT_PATH: ${{ steps.azure-fileshare.outputs.MNT_PATH }}
+    #     MOUNT_FS: ${{ inputs.has-azure-credentials == 'true' && inputs.is_unit_test == 'false' }}
+    #   run: |
+    #     ARG=("")
 
-        if [[ "$MOUNT_FS" == "true" ]]; then
-          ARG+=("--volume $MNT_PATH/TestData:/home/TestData")
-        fi
+    #     if [[ "$MOUNT_FS" == "true" ]]; then
+    #       ARG+=("--volume $MNT_PATH/TestData:/home/TestData")
+    #     fi
 
-        if [[ "${{ inputs.cpu-only }}" == "false" ]]; then
-          ARG+=("--runtime=nvidia --gpus all")
-        fi
+    #     if [[ "${{ inputs.cpu-only }}" == "false" ]]; then
+    #       ARG+=("--runtime=nvidia --gpus all")
+    #     fi
 
-        cmd=$(cat <<RUN_TEST_EOF
-        #!/bin/bash
-        docker container rm -f nemo_container_${{ github.run_id }} || true
-        docker run \
-          --rm \
-          -d \
-          --name nemo_container_${{ github.run_id }} \
-          ${ARG[@]} \
-          --shm-size=64g \
-          --env TRANSFORMERS_OFFLINE=0 \
-          --env HYDRA_FULL_ERROR=1 \
-          --env HF_HOME=/home/TestData/HF_HOME \
-          --env RUN_ID=${{ github.run_id }} \
-          --workdir /workspace \
-          --volume $(pwd)/Export-Deploy:/workspace \
-          export-deploy \
-          bash -c "sleep $(( ${{ inputs.timeout }} * 60 + 60 ))"
-        RUN_TEST_EOF
-        )
+    #     cmd=$(cat <<RUN_TEST_EOF
+    #     #!/bin/bash
+    #     docker container rm -f nemo_container_${{ github.run_id }} || true
+    #     docker run \
+    #       --rm \
+    #       -d \
+    #       --name nemo_container_${{ github.run_id }} \
+    #       ${ARG[@]} \
+    #       --shm-size=64g \
+    #       --env TRANSFORMERS_OFFLINE=0 \
+    #       --env HYDRA_FULL_ERROR=1 \
+    #       --env HF_HOME=/home/TestData/HF_HOME \
+    #       --env RUN_ID=${{ github.run_id }} \
+    #       --workdir /workspace \
+    #       --volume $(pwd)/Export-Deploy:/workspace \
+    #       export-deploy \
+    #       bash -c "sleep $(( ${{ inputs.timeout }} * 60 + 60 ))"
+    #     RUN_TEST_EOF
+    #     )
 
-        echo "$cmd" | tee "retry_job.sh"
-        bash retry_job.sh
+    #     echo "$cmd" | tee "retry_job.sh"
+    #     bash retry_job.sh
 
-    - name: Create run-script
-      id: create
-      shell: bash
-      run: |
-        COVERAGE_PREFIX=$([[ "${{ inputs.is_unit_test }}" == "true" ]] && echo "unit-test" || echo "e2e")
-        echo "coverage-prefix=$COVERAGE_PREFIX" | tee -a "$GITHUB_OUTPUT"
+    # - name: Create run-script
+    #   id: create
+    #   shell: bash
+    #   run: |
+    #     COVERAGE_PREFIX=$([[ "${{ inputs.is_unit_test }}" == "true" ]] && echo "unit-test" || echo "e2e")
+    #     echo "coverage-prefix=$COVERAGE_PREFIX" | tee -a "$GITHUB_OUTPUT"
 
-        cmd=$(cat <<'RUN_TEST_EOF'
-        #!/bin/bash
+    #     cmd=$(cat <<'RUN_TEST_EOF'
+    #     #!/bin/bash
 
-        docker exec -t nemo_container_${{ github.run_id }} bash -c '
-          set -e
-          bash tests/${{ inputs.is_unit_test == 'true' && 'unit_tests' || 'functional_tests' }}/${{ inputs.script }}.sh
-        '
+    #     docker exec -t nemo_container_${{ github.run_id }} bash -c '
+    #       set -e
+    #       bash tests/${{ inputs.is_unit_test == 'true' && 'unit_tests' || 'functional_tests' }}/${{ inputs.script }}.sh
+    #     '
 
-        RUN_TEST_EOF
-        )
+    #     RUN_TEST_EOF
+    #     )
 
-        echo "timeout_in_seconds=$(( ${{ inputs.timeout }} * 60 ))" | tee -a "$GITHUB_OUTPUT"
-        echo "$cmd" | tee "job.sh"
+    #     echo "timeout_in_seconds=$(( ${{ inputs.timeout }} * 60 ))" | tee -a "$GITHUB_OUTPUT"
+    #     echo "$cmd" | tee "job.sh"
 
-    - name: Run main script
-      uses: nick-fields/retry@v3
-      id: run-main-script
-      with:
-        timeout_seconds: ${{ steps.create.outputs.timeout_in_seconds }}
-        max_attempts: 3
-        shell: bash
-        retry_on: timeout
-        command: /bin/bash job.sh
-        on_retry_command: /bin/bash retry_job.sh
+    # - name: Run main script
+    #   uses: nick-fields/retry@v3
+    #   id: run-main-script
+    #   with:
+    #     timeout_seconds: ${{ steps.create.outputs.timeout_in_seconds }}
+    #     max_attempts: 3
+    #     shell: bash
+    #     retry_on: timeout
+    #     command: /bin/bash job.sh
+    #     on_retry_command: /bin/bash retry_job.sh
 
-    - name: Check result
-      id: check
-      shell: bash
-      run: |
-        docker exec nemo_container_${{ github.run_id }} /opt/venv/bin/coverage combine || true
-        docker exec nemo_container_${{ github.run_id }} /opt/venv/bin/coverage xml
-        docker cp nemo_container_${{ github.run_id }}:/workspace/.coverage .coverage
-        docker cp nemo_container_${{ github.run_id }}:/workspace/coverage.xml coverage.xml
+    # - name: Check result
+    #   id: check
+    #   shell: bash
+    #   run: |
+    #     docker exec nemo_container_${{ github.run_id }} /opt/venv/bin/coverage combine || true
+    #     docker exec nemo_container_${{ github.run_id }} /opt/venv/bin/coverage xml
+    #     docker cp nemo_container_${{ github.run_id }}:/workspace/.coverage .coverage
+    #     docker cp nemo_container_${{ github.run_id }}:/workspace/coverage.xml coverage.xml
 
-        coverage_report=coverage-${{ steps.create.outputs.coverage-prefix }}-${{ github.run_id }}-$(uuidgen)
-        echo "coverage_report=$coverage_report" >> "$GITHUB_OUTPUT"
+    #     coverage_report=coverage-${{ steps.create.outputs.coverage-prefix }}-${{ github.run_id }}-$(uuidgen)
+    #     echo "coverage_report=$coverage_report" >> "$GITHUB_OUTPUT"
 
-        EXIT_CODE=${{ steps.run-main-script.outputs.exit_code }}
-        IS_SUCCESS=$([[ "$EXIT_CODE" -eq 0 ]] && echo "true" || echo "false")
+    #     EXIT_CODE=${{ steps.run-main-script.outputs.exit_code }}
+    #     IS_SUCCESS=$([[ "$EXIT_CODE" -eq 0 ]] && echo "true" || echo "false")
 
-        if [[ "$IS_SUCCESS" == "false" && "${{ inputs.is_optional }}" == "true" ]]; then
-          echo "::warning:: Test failed, but displayed as successful because it is marked as optional."
-          IS_SUCCESS=true
-        fi
+    #     if [[ "$IS_SUCCESS" == "false" && "${{ inputs.is_optional }}" == "true" ]]; then
+    #       echo "::warning:: Test failed, but displayed as successful because it is marked as optional."
+    #       IS_SUCCESS=true
+    #     fi
 
-        if [[ "$IS_SUCCESS" == "false" ]]; then
-          echo Test did not finish successfully.
-          exit 1
-        fi
+    #     if [[ "$IS_SUCCESS" == "false" ]]; then
+    #       echo Test did not finish successfully.
+    #       exit 1
+    #     fi
 
-        exit $EXIT_CODE
+    #     exit $EXIT_CODE
 
-    - name: Test coverage
-      shell: bash -x -e -u -o pipefail {0}
-      run: |
-        docker exec -t nemo_container_${{ github.run_id }} /opt/venv/bin/coverage report -i
+    # - name: Test coverage
+    #   shell: bash -x -e -u -o pipefail {0}
+    #   run: |
+    #     docker exec -t nemo_container_${{ github.run_id }} /opt/venv/bin/coverage report -i
 
-    - name: Upload artifacts
-      uses: actions/upload-artifact@v4
-      if: ${{ steps.check.outputs.coverage_report != 'none' }}
-      with:
-        name: ${{ steps.check.outputs.coverage_report }}
-        path: |
-          coverage.xml
-          .coverage
-        include-hidden-files: true
+    # - name: Upload artifacts
+    #   uses: actions/upload-artifact@v4
+    #   if: ${{ steps.check.outputs.coverage_report != 'none' }}
+    #   with:
+    #     name: ${{ steps.check.outputs.coverage_report }}
+    #     path: |
+    #       coverage.xml
+    #       .coverage
+    #     include-hidden-files: true
