test
Signed-off-by: oliver könig <okoenig@nvidia.com>

diff --git a/.github/workflows/cicd-main.yml b/.github/workflows/cicd-main.yml
--- a/.github/workflows/cicd-main.yml
+++ b/.github/workflows/cicd-main.yml
@@ -104,184 +104,189 @@ jobs:
       AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
       AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
-  cicd-main-unit-tests:
-    needs: [pre-flight, cicd-test-container-build]
-    uses: ./.github/workflows/cicd-main-unit-tests.yml
-    if: |
-      (
-        success()
-        || (
-          needs.cicd-wait-in-queue.result == 'skipped'
-          && needs.pre-flight.outputs.is_ci_workload == 'true'
-        )
-      )
-      && !cancelled()
-    with:
-      test_to_run: ${{ needs.pre-flight.outputs.test_to_run }}
+  # cicd-main-unit-tests:
+  #   needs: [pre-flight, cicd-test-container-build]
+  #   uses: ./.github/workflows/cicd-main-unit-tests.yml
+  #   if: |
+  #     (
+  #       success()
+  #       || (
+  #         needs.cicd-wait-in-queue.result == 'skipped'
+  #         && needs.pre-flight.outputs.is_ci_workload == 'true'
+  #       )
+  #     )
+  #     && !cancelled()
+  #   with:
+  #     test_to_run: ${{ needs.pre-flight.outputs.test_to_run }}
 
-  cicd-main-e2e-tests:
-    needs: [pre-flight, cicd-test-container-build, cicd-main-unit-tests]
-    uses: ./.github/workflows/cicd-main-e2e-tests.yml
-    if: |
-      (
-        success()
-        || (
-          needs.cicd-wait-in-queue.result == 'skipped'
-          && needs.pre-flight.outputs.is_ci_workload == 'true'
-        )
-      )
-      && !cancelled()
-    with:
-      test_to_run: ${{ needs.pre-flight.outputs.test_to_run }}
+  #   secrets:
+  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
-  Nemo_CICD_Test:
-    needs:
-      - pre-flight
-      - cicd-test-container-build
-      - cicd-main-unit-tests
-      - cicd-main-e2e-tests
-    if: always()
-    runs-on: ubuntu-latest
-    permissions: write-all
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+  # cicd-main-e2e-tests:
+  #   needs: [pre-flight, cicd-test-container-build, cicd-main-unit-tests]
+  #   uses: ./.github/workflows/cicd-main-e2e-tests.yml
+  #   if: |
+  #     (
+  #       success()
+  #       || (
+  #         needs.cicd-wait-in-queue.result == 'skipped'
+  #         && needs.pre-flight.outputs.is_ci_workload == 'true'
+  #       )
+  #     )
+  #     && !cancelled()
+  #   with:
+  #     test_to_run: ${{ needs.pre-flight.outputs.test_to_run }}
 
-      - name: Get workflow result
-        id: result
-        env:
-          GH_TOKEN: ${{ github.token }}
-          RUN_ID: ${{ github.run_id }}
-          HAS_LABEL: ${{ github.event.label.name == 'Run CICD' }}
-          IS_SCHEDULED: ${{ github.event_name == 'schedule' }}
-        run: |
-          # Get workflow run details and check job conclusions
-          LATEST_ATTEMPT=$(gh run view $RUN_ID --json jobs -q '[.jobs[] | select(.conclusion != null) | .conclusion] | last')
-          NUM_FAILED=$(gh run view $RUN_ID --json jobs -q '[.jobs[] | select(.conclusion == "failure") | .name] | length')
-          NUM_CANCELLED=$(gh run view $RUN_ID --json jobs -q '[.jobs[] | select(.conclusion == "cancelled") | .name] | length')
+  # Nemo_CICD_Test:
+  #   needs:
+  #     - pre-flight
+  #     - cicd-test-container-build
+  #     - cicd-main-unit-tests
+  #     - cicd-main-e2e-tests
+  #   if: always()
+  #   runs-on: ubuntu-latest
+  #   permissions: write-all
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
 
-          if [[ $NUM_FAILED -eq 0 && $NUM_CANCELLED -eq 0 && ("$HAS_LABEL" == "true" || "$IS_SCHEDULED" == "true") ]]; then
-            RESULT="success"
-          elif [[ $NUM_CANCELLED -gt 0 ]]; then
-            RESULT="cancelled"
-          else
-            RESULT="failure"
-          fi
+  #     - name: Get workflow result
+  #       id: result
+  #       env:
+  #         GH_TOKEN: ${{ github.token }}
+  #         RUN_ID: ${{ github.run_id }}
+  #         HAS_LABEL: ${{ github.event.label.name == 'Run CICD' }}
+  #         IS_SCHEDULED: ${{ github.event_name == 'schedule' }}
+  #       run: |
+  #         # Get workflow run details and check job conclusions
+  #         LATEST_ATTEMPT=$(gh run view $RUN_ID --json jobs -q '[.jobs[] | select(.conclusion != null) | .conclusion] | last')
+  #         NUM_FAILED=$(gh run view $RUN_ID --json jobs -q '[.jobs[] | select(.conclusion == "failure") | .name] | length')
+  #         NUM_CANCELLED=$(gh run view $RUN_ID --json jobs -q '[.jobs[] | select(.conclusion == "cancelled") | .name] | length')
 
-          # Output the final status
-          echo "code=$RESULT" | tee -a $GITHUB_OUTPUT
+  #         if [[ $NUM_FAILED -eq 0 && $NUM_CANCELLED -eq 0 && ("$HAS_LABEL" == "true" || "$IS_SCHEDULED" == "true") ]]; then
+  #           RESULT="success"
+  #         elif [[ $NUM_CANCELLED -gt 0 ]]; then
+  #           RESULT="cancelled"
+  #         else
+  #           RESULT="failure"
+  #         fi
 
-      - name: Checkout for GH CLI
-        uses: actions/checkout@v4
+  #         # Output the final status
+  #         echo "code=$RESULT" | tee -a $GITHUB_OUTPUT
 
-      - name: Remove label if not cancelled
-        if: |
-          steps.result.outputs.code != 'cancelled' 
-          && github.event.label.name == 'Run CICD' 
-          && github.event.pull_request.head.repo.full_name == github.repository
-        env:
-          GH_TOKEN: ${{ github.token }}
-          PR_NUMBER: ${{ github.event.number }}
-        run: gh pr edit "$PR_NUMBER" --remove-label "Run CICD"
+  #     - name: Checkout for GH CLI
+  #       uses: actions/checkout@v4
 
-      - name: Pipeline successful, add PR comment
-        if: |
-          steps.result.outputs.code == 'success' 
-          && github.event_name == 'pull_request' 
-          && env.SLACK_WEBHOOK != ''
-        uses: peter-evans/create-or-update-comment@v4
-        env:
-          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
-          REPOSITORY: ${{ github.repository }}
-          RUN_ID: ${{ github.run_id }}
-        with:
-          issue-number: ${{ github.event.number }}
-          body: |
-            [🤖]: Hi @${{ github.event.pull_request.user.login }} 👋,
+  #     - name: Remove label if not cancelled
+  #       if: |
+  #         steps.result.outputs.code != 'cancelled'
+  #         && github.event.label.name == 'Run CICD'
+  #         && github.event.pull_request.head.repo.full_name == github.repository
+  #       env:
+  #         GH_TOKEN: ${{ github.token }}
+  #         PR_NUMBER: ${{ github.event.number }}
+  #       run: gh pr edit "$PR_NUMBER" --remove-label "Run CICD"
 
-            We wanted to let you know that a [CICD pipeline](https://github.com/${{ env.REPOSITORY }}/actions/runs/${{ env.RUN_ID }}) for this PR just finished successfully.
+  #     - name: Pipeline successful, add PR comment
+  #       if: |
+  #         steps.result.outputs.code == 'success'
+  #         && github.event_name == 'pull_request'
+  #         && env.SLACK_WEBHOOK != ''
+  #       uses: peter-evans/create-or-update-comment@v4
+  #       env:
+  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+  #         REPOSITORY: ${{ github.repository }}
+  #         RUN_ID: ${{ github.run_id }}
+  #       with:
+  #         issue-number: ${{ github.event.number }}
+  #         body: |
+  #           [🤖]: Hi @${{ github.event.pull_request.user.login }} 👋,
 
-            So it might be time to merge this PR or get some approvals.
+  #           We wanted to let you know that a [CICD pipeline](https://github.com/${{ env.REPOSITORY }}/actions/runs/${{ env.RUN_ID }}) for this PR just finished successfully.
 
-            //cc @chtruong814 @ko3n1g @pablo-garay @thomasdhc
+  #           So it might be time to merge this PR or get some approvals.
 
-      - name: "Pipeline not successful and not cancelled: Send Slack alert & create step summary"
-        if: |
-          steps.result.outputs.code == 'failure' 
-          && github.event.label.name == 'Run CICD' 
-          && env.SLACK_WEBHOOK != ''
-        env:
-          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          REPOSITORY: ${{ github.repository }}
-          RUN_ID: ${{ github.run_id }}
-          PR_NUMBER: ${{ github.event.number }}
-          SERVER_URL: ${{ github.server_url }}
-        run: |
-          set -x
-          pip install PyGithub
-          export BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
+  #           //cc @chtruong814 @ko3n1g @pablo-garay @thomasdhc
 
-          python .github/scripts/notify.py
+  #     - name: "Pipeline not successful and not cancelled: Send Slack alert & create step summary"
+  #       if: |
+  #         steps.result.outputs.code == 'failure'
+  #         && github.event.label.name == 'Run CICD'
+  #         && env.SLACK_WEBHOOK != ''
+  #       env:
+  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #         REPOSITORY: ${{ github.repository }}
+  #         RUN_ID: ${{ github.run_id }}
+  #         PR_NUMBER: ${{ github.event.number }}
+  #         SERVER_URL: ${{ github.server_url }}
+  #       run: |
+  #         set -x
+  #         pip install PyGithub
+  #         export BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
 
-      - name: Exit
-        if: ${{ always() }}
-        env:
-          RESULT: ${{ steps.result.outputs.code }}
-        run: |
-          if [ $RESULT == "success" ]; then
-            exit 0
-          else
-            exit 1
-          fi
+  #         python .github/scripts/notify.py
 
-  Coverage:
-    runs-on: ubuntu-latest
-    needs: [pre-flight, Nemo_CICD_Test]
-    if: |
-      needs.pre-flight.outputs.test_to_run != '[]'
-      && needs.pre-flight.outputs.components_to_run != '[]'
-      && (
-        success() 
-        || needs.Nemo_CICD_Test.result == 'success'
-      )
-      && !cancelled()
-    strategy:
-      matrix:
-        flag: [unit-test, e2e]
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+  #     - name: Exit
+  #       if: ${{ always() }}
+  #       env:
+  #         RESULT: ${{ steps.result.outputs.code }}
+  #       run: |
+  #         if [ $RESULT == "success" ]; then
+  #           exit 0
+  #         else
+  #           exit 1
+  #         fi
 
-      - name: Download coverage reports of current branch
-        uses: actions/download-artifact@v4
-        with:
-          pattern: coverage-${{ matrix.flag }}-*
+  # Coverage:
+  #   runs-on: ubuntu-latest
+  #   needs: [pre-flight, Nemo_CICD_Test]
+  #   if: |
+  #     needs.pre-flight.outputs.test_to_run != '[]'
+  #     && needs.pre-flight.outputs.components_to_run != '[]'
+  #     && (
+  #       success()
+  #       || needs.Nemo_CICD_Test.result == 'success'
+  #     )
+  #     && !cancelled()
+  #   strategy:
+  #     matrix:
+  #       flag: [unit-test, e2e]
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
 
-      - name: Get total coverage of current branch
-        shell: bash -x -e -u -o pipefail {0}
-        if: always()
-        run: |
-          pip install coverage
+  #     - name: Download coverage reports of current branch
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         pattern: coverage-${{ matrix.flag }}-*
 
-          ls -al .
-          ls -al coverage-*/
-          coverage combine --keep $(ls coverage-*/.coverage)
-          coverage report -i
-          rm -rf coverage-*
-          ls -al
+  #     - name: Get total coverage of current branch
+  #       shell: bash -x -e -u -o pipefail {0}
+  #       if: always()
+  #       run: |
+  #         pip install coverage
 
-      - name: Upload coverage reports to Codecov
-        uses: codecov/codecov-action@v5
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }}
-          verbose: true
-          flags: ${{ matrix.flag }}
+  #         ls -al .
+  #         ls -al coverage-*/
+  #         coverage combine --keep $(ls coverage-*/.coverage)
+  #         coverage report -i
+  #         rm -rf coverage-*
+  #         ls -al
 
-      - name: Upload artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: coverage-${{ matrix.flag }}-aggregated
-          path: |
-            .coverage
-          include-hidden-files: true
+  #     - name: Upload coverage reports to Codecov
+  #       uses: codecov/codecov-action@v5
+  #       with:
+  #         token: ${{ secrets.CODECOV_TOKEN }}
+  #         verbose: true
+  #         flags: ${{ matrix.flag }}
+
+  #     - name: Upload artifacts
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: coverage-${{ matrix.flag }}-aggregated
+  #         path: |
+  #           .coverage
+  #         include-hidden-files: true
